server {
    listen 8080;
    include /etc/nginx/conf.d/lxdpanel-common.inc;
}
server {
    listen 80;
    include /etc/nginx/conf.d/lxdpanel-common.inc;
}
server {
    listen 443 ssl;
    ssl_certificate     /etc/nginx/ssl/lxdpanel.crt;
    ssl_certificate_key /etc/nginx/ssl/lxdpanel.key;
    include /etc/nginx/conf.d/lxdpanel-common.inc;
}
